# Generated by Django 4.1.1 on 2023-08-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
