# Generated by Django 4.1.1 on 2023-08-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchase_is_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
