# Generated by Django 4.1.1 on 2023-08-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_buycredits'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonetizationOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monetization_on', models.BooleanField(default=False)),
            ],
        ),
    ]
