# Generated by Django 4.1.1 on 2023-08-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_vifurushi'),
    ]

    operations = [
        migrations.AddField(
            model_name='vifurushi',
            name='token_amount',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
