# Generated by Django 4.1.1 on 2023-08-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauthentication', '0003_customuser_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='credits',
        ),
    ]
