# Generated by Django 4.1.1 on 2023-08-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauthentication', '0004_remove_customuser_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
